name: flutterLee
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  dio: ^3.0.6
  flutter_swiper: ^1.1.3
  share: ^0.6.1+1
  shared_preferences: ^0.5.3+4
  pull_to_refresh: 1.6.3
  dio_cookie_manager: ^1.0.0

  #JSON to Model
  json_annotation: ^3.1.1

  #国际化 时间格式化
  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  #JSON to Model
  build_runner:  ^1.11.0
  json_serializable: ^3.5.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/WeatherIcon - 1-1.png
    - images/WeatherIcon - 1-2.png
    - images/WeatherIcon - 1-3.png
    - images/WeatherIcon - 1-4.png
    - images/WeatherIcon - 1-5.png
    - images/WeatherIcon - 1-6.png
    - images/WeatherIcon - 1-7.png
    - images/WeatherIcon - 1-8.png
    - images/WeatherIcon - 1-9.png
    - images/WeatherIcon - 1-10.png
    - images/WeatherIcon - 1-11.png
    - images/WeatherIcon - 1-12.png    
    - images/WeatherIcon - 1-12.png
    - images/WeatherIcon - 1-14.png
    - images/WeatherIcon - 1-15.png
    - images/WeatherIcon - 1-16.png
    - images/WeatherIcon - 1-17.png
    - images/WeatherIcon - 1-18.png
    - images/WeatherIcon - 1-19.png
    - images/WeatherIcon - 1-20.png
    - images/WeatherIcon - 1-21.png
    - images/WeatherIcon - 1-22.png
    - images/WeatherIcon - 1-23.png
    - images/WeatherIcon - 1-24.png 
    - images/WeatherIcon - 1-25.png
    - images/WeatherIcon - 1-26.png
    - images/WeatherIcon - 1-27.png
    - images/WeatherIcon - 1-28.png
    - images/WeatherIcon - 1-29.png
    - images/WeatherIcon - 1-30.png
    - images/WeatherIcon - 1-31.png
    - images/WeatherIcon - 1-32.png
    - images/WeatherIcon - 1-33.png
    - images/WeatherIcon - 1-34.png
    - images/WeatherIcon - 1-35.png
    - images/WeatherIcon - 1-36.png 
    - images/WeatherIcon - 1-37.png
    - images/WeatherIcon - 1-38.png
    - images/WeatherIcon - 1-39.png
    - images/WeatherIcon - 1-40.png
    - images/WeatherIcon - 1-41.png
    - images/WeatherIcon - 1-42.png
    - images/WeatherIcon - 1-43.png
    - images/WeatherIcon - 1-44.png
    - images/WeatherIcon - 1-45.png
    - images/WeatherIcon - 1-46.png
    - images/WeatherIcon - 1-47.png
    - images/WeatherIcon - 1-48.png
    - images/WeatherIcon - 1-49.png
    - images/WeatherIcon - 1-50.png
    - images/WeatherIcon - 1-51.png
    - images/WeatherIcon - 1-52.png
    - images/WeatherIcon - 1-53.png
    - images/WeatherIcon - 1-54.png
    - images/WeatherIcon - 1-55.png
    - images/WeatherIcon - 1-56.png
    - images/WeatherIcon - 1-57.png
    - images/WeatherIcon - 1-58.png
    - images/WeatherIcon - 1-59.png
    - images/WeatherIcon - 1-60.png 
    - images/WeatherIcon - 1-61.png
    - images/WeatherIcon - 1-62.png
    - images/WeatherIcon - 1-63.png
    - images/WeatherIcon - 1-64.png
    - images/WeatherIcon - 1-65.png
    - images/WeatherIcon - 1-66.png
    - images/WeatherIcon - 1-67.png
    - images/WeatherIcon - 1-68.png
    - images/WeatherIcon - 1-69.png
    - images/WeatherIcon - 1-70.png
    - images/WeatherIcon - 1-71.png
    - images/WeatherIcon - 1-72.png
    - lib/page/models/city.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PingFang
      fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
          - asset: fonts/PingFang_Bold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
